### ISSUE TITLE
Reporting?

### ISSUE THREAD

**Issue by AndrewGorton** [cgi-digital/DigitalMarketplaceAlerter#5]
As an administrator
I want to produce reports
So that I don't have to manually create graphs

Probably only useful after #4 is done (and definitely want #2)

**Comment by AndrewGorton** [comment]
Not clear quite what reports need creating.

Currently we do a line graph of total cumulative opportunities advertised -v- cumulative opportunities bid for, and stacked bar of response type by Bid Manager to date. We also produce a table showing where total oppportunities cost, the value of the ones we're qualifying on, and the ones we're bidding on.

**Comment by mariosk89** [comment]
@AndrewGorton When you say "Currently we do a line graph..." what exactly do you mean? Is this graph generated using other external tools like Excel for example? Is this task about integrating the generation of this graph into this system?

**Comment by mariosk89** [comment]
We could generate a number of reports, given the information that we have at the moment:

1. Opportunities per location
2. Opportunities per customer
3. Accumulative Opportunities v Bids (time diagram)
4. Table showing where total opportunities cost, the value of the ones we're qualifying on, and the ones we're bidding on
5. Opportunity responses (per week/month/etc)

For 3, 4 and 5 we'll need to update our current schema to include a bid status (did we make a bid for this opportunity?) and the bid response status (how did the customer responded to our bid?)

**Comment by AndrewGorton** [comment]
Basic reports now running in Live.
